set(_CATKIN_CURRENT_PACKAGE "ack_mqtt")
set(ack_mqtt_VERSION "0.0.0")
set(ack_mqtt_MAINTAINER "seth <seth@todo.todo>")
set(ack_mqtt_PACKAGE_FORMAT "2")
set(ack_mqtt_BUILD_DEPENDS "rosbridge_library" "roscpp" "std_msgs")
set(ack_mqtt_BUILD_EXPORT_DEPENDS "rosbridge_library" "roscpp" "std_msgs")
set(ack_mqtt_BUILDTOOL_DEPENDS "catkin")
set(ack_mqtt_BUILDTOOL_EXPORT_DEPENDS )
set(ack_mqtt_EXEC_DEPENDS "rosbridge_library" "roscpp" "std_msgs")
set(ack_mqtt_RUN_DEPENDS "rosbridge_library" "roscpp" "std_msgs")
set(ack_mqtt_TEST_DEPENDS )
set(ack_mqtt_DOC_DEPENDS )
set(ack_mqtt_URL_WEBSITE "")
set(ack_mqtt_URL_BUGTRACKER "")
set(ack_mqtt_URL_REPOSITORY "")
set(ack_mqtt_DEPRECATED "")